package io.github.chenxiex.calibrecloud.auth

import java.net.URI
import java.net.URLDecoder
import java.nio.charset.StandardCharsets

/**
 * Validates a callback against one in-memory authorization transaction before code exchange.
 * The coordinator restores the pending request from encrypted storage before calling [begin].
 * Use a monotonic clock for both [begin] and [consumeCallback]. Never log result credentials.
 */
class AuthorizationTransactionGate(
    private val configuration: OneDriveOAuthConfiguration,
    private val lifetimeMillis: Long = 10 * 60 * 1_000L,
) {
    private data class Pending(val state: String, val createdAtMillis: Long)

    private var pending: Pending? = null

    init {
        require(lifetimeMillis > 0)
    }

    /** The state must be the random value generated by AppAuth for the browser request. */
    @Synchronized
    fun begin(state: String, createdAtMillis: Long) {
        require(state.isNotEmpty())
        check(pending == null) { "An authorization transaction is already pending" }
        pending = Pending(state, createdAtMillis)
    }

    /** Discards the browser transaction without changing an existing stored authorization. */
    @Synchronized
    fun cancel(): Boolean {
        val existed = pending != null
        pending = null
        return existed
    }

    /**
     * Only a matching code or OAuth error consumes the transaction. Rejected unrelated callbacks
     * leave it available; expiry clears it. The caller must exchange a returned code only once.
     */
    @Synchronized
    fun consumeCallback(address: String, nowMillis: Long): CallbackResult {
        val transaction = pending ?: return CallbackResult.Rejected(Rejection.NO_PENDING)
        val age = nowMillis - transaction.createdAtMillis
        if (nowMillis < transaction.createdAtMillis || age < 0 || age >= lifetimeMillis) {
            pending = null
            return CallbackResult.Rejected(Rejection.EXPIRED)
        }
        if (!configuration.acceptsCallback(address)) {
            return CallbackResult.Rejected(Rejection.ADDRESS_MISMATCH)
        }
        val parameters = try {
            URI(address).rawQuery?.split('&')?.map { parameter ->
                val parts = parameter.split('=', limit = 2)
                decode(parts[0]) to decode(parts.getOrElse(1) { "" })
            }.orEmpty()
        } catch (_: IllegalArgumentException) {
            return CallbackResult.Rejected(Rejection.INVALID_PARAMETERS)
        }
        val states = parameters.filter { it.first == "state" }.map { it.second }
        val codes = parameters.filter { it.first == "code" }.map { it.second }
        val errors = parameters.filter { it.first == "error" }.map { it.second }
        if (states.size != 1 || codes.size > 1 || errors.size > 1 ||
            codes.size + errors.size != 1 || codes.any { it.isEmpty() } || errors.any { it.isEmpty() }
        ) {
            return CallbackResult.Rejected(Rejection.INVALID_PARAMETERS)
        }
        if (states.single() != transaction.state) {
            return CallbackResult.Rejected(Rejection.STATE_MISMATCH)
        }
        pending = null
        return if (codes.isNotEmpty()) {
            CallbackResult.Code(codes.single())
        } else {
            CallbackResult.OAuthError(errors.single())
        }
    }

    private fun decode(value: String): String = URLDecoder.decode(value, StandardCharsets.UTF_8.name())

    sealed interface CallbackResult {
        class Code(val code: String) : CallbackResult
        class OAuthError(val error: String) : CallbackResult
        data class Rejected(val reason: Rejection) : CallbackResult
    }

    enum class Rejection {
        NO_PENDING,
        EXPIRED,
        ADDRESS_MISMATCH,
        INVALID_PARAMETERS,
        STATE_MISMATCH,
    }
}
